version: "3.8"

services:
  pocketbase:
    image: spectado/pocketbase:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - 8090:80
    volumes:
      - ./pocketbase-db:/pb_data
